<?php
/**
 * attribute-code and attribute-id attributes are fallback for Magento versions prior to 2.4
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block*/

$config = $block->getConfig();
$swatchConfig = $block->getSwatchConfig();
$sizeConfig = $block->getSizeConfig();
$classes = $block->getClasses();
?>

<?php foreach ($config['attributes'] as $attributeId => $attribute): ?>
    <?php
    $attributeCode = $attribute['code'];
    $attributeLabel = $attribute['label'];
    $attributeLabelId = "option-label-$attributeCode-$attributeId";
    $attributeLabelClass = $classes['attribute_label'];
    $attributeSelectedClass = $classes['attribute_selected_option'];

    if (!$block->getEnableControlLabel()) {
        $attributeLabelClass .= ' visually-hidden';
        $attributeSelectedClass .= ' visually-hidden';
    }
    ?>
    <div
        class="<?= $block->escapeHtml($classes['attribute'] . ' ' . $attributeCode) ?>"
        data-attribute-code="<?= $block->escapeHtml($attributeCode) ?>"
        data-attribute-id="<?= $block->escapeHtml($attributeId) ?>"
        attribute-code="<?= $block->escapeHtml($attributeCode) ?>"
        attribute-id="<?= $block->escapeHtml($attributeId) ?>"
    >
        <span
            id="<?= $block->escapeHtml($attributeLabelId) ?>"
            class="<?= $block->escapeHtml($attributeLabelClass) ?>"
        ><?= $block->escapeHtml($attributeLabel) ?></span>
        <span class="<?= $block->escapeHtml($attributeSelectedClass) ?>"></span>
        <div
            aria-activedescendant=""
            tabindex="0"
            aria-invalid="false"
            aria-required="true"
            role="listbox"
            aria-labelledby="<?= $block->escapeHtml($attributeLabelId) ?>"
            class="<?= $block->escapeHtml($classes['attribute_options_wrapper']) ?>"
        >
        <?php
        if (isset($swatchConfig[$attributeId])) {
            $attributeConfig = $swatchConfig[$attributeId];
            $displayedOptions = 0;

            $swatchOption = $block
                ->getChildBlock('swatch_option')
                ->setSizeConfig($sizeConfig)
                ->setAttributeLabelId($attributeLabelId)
                ->setClasses($classes);

            foreach ($attribute['options'] as $optionIndex => $option) {
                $optionId = $option['id'];
                $optionConfig = $attributeConfig[$optionId] ?? null;

                if (!$optionConfig) {
                    continue;
                }

                if ($block->getMoreButtonLimit() === $displayedOptions++) {
                    $moreButtonClass = $classes['more_button'];
                    $moreButtonText = $block->getMoreButtonText();
                    echo '<a href="#" class="' . $block->escapeHtml($moreButtonClass) .'"><span>' .
                        $block->escapeHtml($moreButtonText) . '</span></a>';
                }

                echo $swatchOption->setOption($option)
                    ->setOptionConfig($optionConfig)
                    ->setIndex($optionIndex)
                    ->toHtml();
            }
        } else {
            if (!$block->getOnlySwatches()) {
                echo $block->getChildBlock('swatch_select')
                ->setData('attribute', $attribute)
                ->setChooseText($block->getChooseText())
                ->setClasses($classes)
                ->toHtml();
            }
        }
        ?>
        </div>
        <input
            class="<?= $block->escapeHtml($classes['attribute_input']) ?> super-attribute-select"
            name="super_attribute[<?= $block->escapeHtml($attributeId) ?>]"
            value=""
            type="text"
            data-selector="super_attribute[<?= $block->escapeHtml($attributeId) ?>]"
            data-validate="{required: true}"
            data-msg-required="<?= __('Please select %1', $block->escapeHtml($attributeLabel)) ?>"
            aria-required="true"
            aria-invalid="false"
        >
    </div>
<?php endforeach; ?>
